trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.Repository.LocalPath)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: AzureCLI@2
  inputs:
    azureSubscription: '67875fb8-3c93-456f-9d1b-add5b41d14b9'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage blob upload-batch -d haartifacts --account-name saartifacts1969 --account-key $(accntKey) -s '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 

  displayName: 'Copy Artifact to Azure Blob Storage'
