trigger:
   - none

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azSubscription)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
        echo "Narendra"
        echo "$(username)"
        echo "$(Passwd)"
  displayName: 'Copy Artifact to Azure Blob Storage'
