trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.Repository.LocalPath)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: AzureCLI@2
  inputs:
    azureSubscription: '67875fb8-3c93-456f-9d1b-add5b41d14b9'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Install AzCopy
      curl -sL https://aka.ms/downloadazcopy-v10-linux | bash
      export PATH=$PATH:/home/$(whoami)/azcopy

      # Copy files to Azure Blob Storage
      azcopy copy "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip" "https://saartifacts1969.blob.core.windows.net/haartifacts/HAProd/Backend/$(Build.BuildId).zip" --recursive

  displayName: 'Copy Artifact to Azure Blob Storage'
